spring:
  application:
    name: Loader data
  datasource:
    url: ${LOADER_DB_JDBC_URL:jdbc:postgresql://localhost:5432/loader}?currentSchema=${spring.jpa.properties.hibernate.default_schema}
    hikari:
      pool-name: HikariCPPool
      driver-class-name: org.postgresql.Driver
      username: ${LOADER_DB_USER:postgres}
      password: ${LOADER_DB_PWD:123}
      connectionTimeout: ${LOADER_DB_TIMEOUT:30000}
      maximum-pool-size: ${LOADER_DB_POOL_SIZE:5}
  jpa:
    properties:
      hibernate:
        default_schema: loader
        show_sql: true

  liquibase:
    default-schema: ${LIQUIBASE_DB_SCHEMA:public}
    driverClassName: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/loader}
    user: ${DB_USER:postgres}
    password: ${DB_PASS:123}
    changeLog: classpath:/db/changelog/db.changelog-master.yaml