spring:
  application:
    name: Loader data
    description: Учебный и тестовый проект по работе с SpringBoot, а также работе с не текстовыми фйлами.
  datasource:
    url: ${LOADER_DB_JDBC_URL:jdbc:postgresql://localhost:5432/loader}?currentSchema=${spring.jpa.properties.hibernate.default_schema}
    hikari:
      pool-name: HikariCPPool
      driver-class-name: org.postgresql.Driver
      username: ${LOADER_DB_USER:postgres}
      password: ${LOADER_DB_PWD:123}
      connectionTimeout: ${LOADER_DB_TIMEOUT:30000}
      maximum-pool-size: ${LOADER_DB_POOL_SIZE:5}
  jpa:
    properties:
      hibernate:
        default_schema: loader
        show_sql: true

config:
  pagination:
    default-limit: 15

server:
  port: 8090