driverClassName: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
jdbcUrl: ${DB_URL:jdbc:postgresql://localhost:5432/loader}
database: ${DB_NAME:loader}
username: ${DB_USER:postgres}
password: ${DB_PASS:123}
poolName: ${DB_POOL_NAME:HikariCPPool}
maxPoolSize: ${DB_POOL_SIZE:1}

spring:
  profiles:
    active: default
  liquibase:
    enabled: true

liquibase:
  profile:  ${LIQUIBASE_PROFILE:default}
  command: ${LIQUIBASE_COMMAND:update}
  tagToRollBackTo: ${TAG_TO_ROLLBACK:v2.0.3}
  dateToRollBackTo: ${DATE_TO_ROLLBACK:}
  dbSchema: ${LIQUIBASE_DB_SCHEMA:public}
  changeLog:
    database: classpath:${CHANGE_LOG_FILE_PATH:db/changelog/changelog-${liquibase.profile}.yml}
  releaseLocks: ${LIQUIBASE_RELEASELOCKS:true}