version: "3"
services:
  database:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: loader
    volumes:
      - ${SERVERS_PATH}/db/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - ${SERVERS_PATH}/redis/data/redis:/data