version: "3"
services:
  database:
    image: postgres:14-alpine.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: loader
    volumes:
      - "loader_data:/var/lib/postgresql/data"

volumes:
  loader_data:
